# 一、基本操作

## 1. 迭代可拆分对象

In [38]:
data=[1,2,3,4]
a,b,c,d = data
a1,*b1, c1 = data
print(a,b,c);print(a1,b1,c1)

1 2 3
1 [2, 3] 4


## 2. 找最大／最小的n个元素

In [39]:
import heapq as hq
data=[1,2,3,4,8,9,10,-3,6,100];n=4
print(hq.nlargest(n, data))
print(hq.nsmallest(n, data))

[100, 10, 9, 8]
[-3, 1, 2, 3]


注意，找最大的时候默认从大到小排序；找最小的时候默认从小到大排序

## 3. 向上向下取整（需要math包）

In [40]:
from math import ceil,floor
a=floor(4.3)
b=ceil(4.3)#ceil有“装天花板”的意思
print("a=",a,";","b=",b)

a= 4 ; b= 5


## 4. 寻找元素的位置

In [41]:
[1,2,3,4].index(2)

1

## 5. list的操作

### 5.1往list里面新增元素

In [42]:
z=[1,2,3];print(z)
z.append(1);print(z)#只添加一个元素到最后
z.extend([2,3]);print(z)#添加多个元素到最后
z.append([11,12]);print(z)#添加的类别可以是list或者其他形式，因为list很包容
# 插入元素（index，元素）：在index处插入，后面的依次退后
z.insert(1, 'a');print(z)

[1, 2, 3]
[1, 2, 3, 1]
[1, 2, 3, 1, 2, 3]
[1, 2, 3, 1, 2, 3, [11, 12]]
[1, 'a', 2, 3, 1, 2, 3, [11, 12]]


注意，append与extend这两个操作都很慢，如果知道最后状态的话最好直接开个大的list

### 5.2 替换及删除一个连续切片

In [43]:
a = [10, 11, 12, 13, 14]
a[1:3] = [1, 2, 3, 4];print(a)#对于步长1的分片，采用整段替换的方法
#上述方法因此也可以用来删除一个连续切片
a[0:3] = [];print(a)

[10, 1, 2, 3, 4, 13, 14]
[3, 4, 13, 14]


### 5.3 删除元素

In [44]:
a = ['a', 1, 'b', 2, 'c'];print(a)
del a[::2];print(a)#从第一位开始，以2为步长删除
##移除某元素i
a = [10, 11, 12, 13, 11];print(a)
a.remove(11);print(a)#移除第一个11，若无元素11会报错
##弹出元素（移除第i位置的元素并打印被移除的元素）
a = [10, 11, 12, 13, 11]
a.pop(2)

['a', 1, 'b', 2, 'c']
[1, 2]
[10, 11, 12, 13, 11]
[10, 12, 13, 11]


12

### 5.4 计算list中某元素出现的次数

In [45]:
a = [11, 12, 13, 12, 11]
a.count(11)

2

### 5.5 列表反向

In [46]:
a=[1,2,3,4]
x=a[::-1];print(x)#不改变原来序列的顺序
a.reverse();print(a)#改变原来序列的顺序

[4, 3, 2, 1]
[4, 3, 2, 1]


### 5.6 排序

In [47]:
a = [10, 1, 11, 13, 11, 2];print(a)
a.sort();print(a)

[10, 1, 11, 13, 11, 2]
[1, 2, 10, 11, 11, 13]


## 6. 自定义函数

In [48]:
def my_factorial(n=5):
    fac = 1
    i=1
    while i <= n:
        fac = fac*i
        i=i+1
    return(fac) 

my_factorial(4)

24

## 7. 从键盘中一次读取多个数值或字符（以空格间隔）

In [49]:
l, m= map(int, input("Please input the number of l, m respectively \
                     and separate it with space: ").split())

x, *y= map(str, input("Please input the number of l, m respectively \
                     and separate it with space: ").split())
print(l,m);print("x = ",x, "y = ",y)

Please input the number of l, m respectively                      and separate it with space: 112 2
Please input the number of l, m respectively                      and separate it with space: 2121 2121 211 21
112 2
x =  2121 y =  ['2121', '211', '21']


## 8. 删除变量

In [50]:
m, n = 1,3;print(m,n)
del m, n
print(m,n)

1 3


NameError: name 'm' is not defined

## 9. 判断一个向量是否包含某元素

In [ ]:
2 in [1,2,5]#list

In [ ]:
import numpy as np
2 in np.array([1,2,5])#array

## 10. 调用外部函数

In [ ]:
import function as f
f.my_factorial()

注：外部函数需要和主程序文档在同一个文件夹下（在本例中为function）

## 11. 返回字典值对应的键

In [ ]:
class_Dict={
'no':0,'yes':1
}
Value=1
list(class_Dict.keys())[list(class_Dict.values()).index(Value)]

## 12. 生成一个随机打乱的序列（用来样本的初始化）

In [ ]:
import random as rd
n=10
idx=rd.sample(range(n),n);print(idx)

## 13. Ipython下的magic命令（类似linux的操作）

### 13. 1 查看所有magic命令

In [ ]:
%lsmagic

### 13.2 查看当前文件夹

In [ ]:
%pwd

### 13.3 查看当前变量空间

In [ ]:
%whos

### 13.4 重置当前变量空间（删除所有的变量）

In [ ]:
%reset -f
%whos

### 13.5 查看当前文件夹下文件

In [ ]:
%ls

### 13.6 生成文件夹

In [ ]:
%mkdir demo_test
%ls

### 13.7 删除文件夹

In [ ]:
%rmdir demo_test

## 14. 数据类型：集合

### 14.1 集合的生成

In [ ]:
s = {2, 3, 4, 2};print("s = ", s)#集合不含相同元素
type(s)

### 14.2 添加元素

In [ ]:
s.add(1);print(s)

### 14.3 集合的交、并

In [ ]:
a = {1, 2, 3, 4}
b = {2, 3, 4, 5}
print(a & b)
print(a | b)

### 14.4 集合的差与对称差

In [ ]:
print(a - b);print(b - a)
print(a ^ b)

### 14.5 判断集合是否存在包含关系

In [ ]:
print(b <= a)
print({1,2,3}<=a)

## 15. 统计DataFrame或series中各元素出现的频数

In [ ]:
import pandas as pd
a=pd.Series(["一本","一本","二本","一本","三本","二本","Null"])
a.value_counts()

## 16. 复数

In [ ]:
a = 1 + 2j
type(a)
Real=a.real;print(Real)#实部
Image=a.imag;print(Image)#虚部
Conjugate=a.conjugate();print(Conjugate)#共轭复数

## 17. 可变与不可变数据类型

<ol>
    <li>可变类型：list, dictionary, set, numpy array, user defined objects
    <li>不可变类型：integer, float, long, complex, string, tuple, frozenset


## 18. 提取符合某条件的列（行）

### 18.1 数据框

In [49]:
data=pd.read_table("iris.txt",sep=",",header=None)
print(data.iloc[:10,:])
data_with_small_column2=data.ix[data.iloc[:,1]<=2.5,:]#提取第二列小于等于2.5的行对应的所有数据
print(data_with_small_column2)

     0    1    2    3            4
0  5.1  3.5  1.4  0.2  Iris-setosa
1  4.9  3.0  1.4  0.2  Iris-setosa
2  4.7  3.2  1.3  0.2  Iris-setosa
3  4.6  3.1  1.5  0.2  Iris-setosa
4  5.0  3.6  1.4  0.2  Iris-setosa
5  5.4  3.9  1.7  0.4  Iris-setosa
6  4.6  3.4  1.4  0.3  Iris-setosa
7  5.0  3.4  1.5  0.2  Iris-setosa
8  4.4  2.9  1.4  0.2  Iris-setosa
9  4.9  3.1  1.5  0.1  Iris-setosa
       0    1    2    3                4
41   4.5  2.3  1.3  0.3      Iris-setosa
53   5.5  2.3  4.0  1.3  Iris-versicolor
57   4.9  2.4  3.3  1.0  Iris-versicolor
60   5.0  2.0  3.5  1.0  Iris-versicolor
62   6.0  2.2  4.0  1.0  Iris-versicolor
68   6.2  2.2  4.5  1.5  Iris-versicolor
69   5.6  2.5  3.9  1.1  Iris-versicolor
72   6.3  2.5  4.9  1.5  Iris-versicolor
80   5.5  2.4  3.8  1.1  Iris-versicolor
81   5.5  2.4  3.7  1.0  Iris-versicolor
87   6.3  2.3  4.4  1.3  Iris-versicolor
89   5.5  2.5  4.0  1.3  Iris-versicolor
93   5.0  2.3  3.3  1.0  Iris-versicolor
98   5.1  2.5  3.0  1.1  Iris-versicolor


//anaconda/envs/python35/lib/python3.5/site-packages/ipykernel/__main__.py:3: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  app.launch_new_instance()


### 18.2 Array

In [57]:
import numpy as np
data=np.array([[1,2,3,4,4],[-1,2,3,-4,10],[1,1,1,1,10],[-3,-2,-3,-2,1]]);print(data)
index=np.where(data[:,1]<1.3);print(index)#提取第二列中小于1.3对应的行
data_with_small_column2=data[index,:];print(data_with_small_column2)
##不像R语言中where的嵌套，如果没有符合的index用来选择array也不会报错
index=np.where(data[:,1]>3);print(index)
data_with_big_column2=data[index,:];print(data_with_big_column2)

[[ 1  2  3  4  4]
 [-1  2  3 -4 10]
 [ 1  1  1  1 10]
 [-3 -2 -3 -2  1]]
(array([2, 3]),)
[[[ 1  1  1  1 10]
  [-3 -2 -3 -2  1]]]
(array([], dtype=int64),)
[]


## 19. 执行命令行的相关操作（os包）

In [ ]:
import os
os.getcwd()#获取当前的工作目录
os.system("ls")#执行"查看当前目录下文件"命令

注：别忘了单条命令要加引号

# 二、数据的读取与存储

In [1]:
import pandas as pd

## 1. 数据的读取

读取时有两个值得注意的点：
1. 在读取的时候要确认好是用什么作为分隔符，比如read_table()默认空格分隔
2. 读取的时候可以哟过dtype选项来选择读取数据的格式，这点在股票数据的读取中极为重要（比如默认数值时000628会被读为628）

### 1.1 读取txt

In [10]:
data_txt=pd.read_table("iris.txt",sep=",",dtype="str",header=None)
data_txt.describe()

0    1    2    3            4
count   150  150  150  150          150
unique   35   23   43   22            3
top     5.0  3.0  1.5  0.2  Iris-setosa
freq     10   26   14   28           50

### 1.2 读取csv

In [9]:
data_csv=pd.read_csv("iris.csv",dtype="str",header=None)#默认逗号分隔
data_csv.describe()

0    1    2    3            4
count   150  150  150  150          150
unique   35   23   43   22            3
top     5.0  3.0  1.5  0.2  Iris-setosa
freq     10   26   14   28           50

### 1.3 读取xls

In [11]:
data_xls=pd.read_excel("iris.xls",dtype="str",header=None)#默认逗号分隔
data_xls.describe()

0    1    2    3            4
count   150  150  150  150          150
unique   35   23   43   22            3
top       5    3  1.5  0.2  Iris-setosa
freq     10   26   14   28           50

## 2. 数据的存储

### 2.1 数据框的存储

In [33]:
import pandas as pd
data=pd.read_excel("iris.xls",dtype="str",header=None).iloc[:10,:]
data.to_csv("data_to_csv.csv",index=False, float_format="str", encoding="utf-8")#保存成csv
data.to_csv("data_to_txt.txt",sep=" ",index=False, float_format="str", encoding="utf-8")#保存成txt

注意：在保存到csv的时候数字会自动当成数值型保存，有时候会与目标不符（比如证券代码000668会被存成668）。即使指定为字符型保存，由于csv的原因，打开时还是会默认显示为数值形式, 此时建议保存为txt。

### 2.2 Array的存储

In [41]:
import numpy as np
data=np.array([[1,2],[2,3]]);
np.savetxt('Array_to_csv.csv', data, delimiter = ',')#保存成csv
np.savetxt('Array_to_txt.txt', data, delimiter = ' ')#保存成txt

array里面的都是数字，如果要保存成字符形式，大概只能先转换成数据框格式再.to_csv()了

In [43]:
import pandas as pd
test=pd.DataFrame(data);print(test)#array转换成DataFrame

   0  1
0  1  2
1  2  3


# 三、Numpy操作

In [ ]:
import numpy as np

## 1. 生成等差数列

In [ ]:
x=np.arange(0,10,1);y=np.arange(3,87,9)
print(x,y)

注： np.arange(min,max,sep) 中min会取到，而max是取不到的

## 2. 求最大最小与寻找其对应位置

In [32]:
a=[1,34,2,34]
max_data=np.max(a);print(max_data)#找到最大的元素
max_index=np.argmax(a);print(max_index)#找到最大的元素所在的第一个位置（若需要求最小的位置函数改为argmin）

34
1


## 3. 使用list构建一个行向量

In [ ]:
a = [1, 2, 3, 40, 5, 6]
b = np.array(a, dtype=float)
print(b);print(np.shape(b))

注：这样生成的维数是（6，）在运算中有时会出现问题，最好转换成（dim，1）。具体方式如下：

In [ ]:
b.shape = (np.shape(b)[0],1);print(np.shape(b))

## 4. 一维结构操作

In [ ]:
b.argmax()#返回最大元所在位置
b.max()#返回最大值
b.mean()#返回平均值
b=b.reshape(2, 3)#重构结构
f = np.repeat([3,4,5], 3);print("f = ", f)#每个元素复制这么多次
g = np.tile([3,4,5], 3);print("g = ", g)#[3,4,5]复制2次(tile:瓦片)

注意，还是存在维度（dim, ）的问题

In [ ]:
print("The dim of g is", np.shape(g))

## 5. 二维结构操作

In [ ]:
d = np.array([[1, 2], [3, 4],[9,8]]);print(d)##里面的每个是行
d.size#元素个数
print(d.T) # 转置
print(d.max(axis=0))# 找维度0的最大值，也就是每一列的最大值
print(d.max(axis=1))# 找维度1的最大值，也就是每一行的最大值
print(d.flatten())# 展开一个numpy数组为1维数组，从上往下拼接每行,是个列向量
print(np.trace(d)) #求迹
x = d

注意，索引的时候修改d有时会导致x也被修改，最好用.copy()操作

In [ ]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]]);print(a)
print(np.dot(a,a)) # 矩阵乘法
print(a*a)# 注意区分 * 乘（对应元素相乘）

## 6. 常用随机矩阵的生成

In [ ]:
a = np.zeros([4,5]);print("a = ",a) # all zero
b = np.ones([7,6]);print("b = ",b) # all one
c = np.eye(4,7);print("c = ",c) # 4x7 diagonal
d = np.diag(range(5));print("d = ",d) # 5x5 diagonal
e = np.empty((2,3));print("e = ",e)
f = np.arange(10, 30, 5);print("f = ",f) # array([10, 15, 20, 25]), 1-D
g = np.linspace(0, 2, 9);print("g = ",g) # 9 numbers from 0 to 2
h = np.random.random((2,3));print("h = ",h) # 随机数矩阵

# 四、Pandas基本操作

## 1. 加载相关包及读取数据

In [22]:
import pandas as pd
# 从外部读取csv并给列命名
data=pd.read_table("iris.txt",sep=",", header=None, encoding="utf-8",\
                   delim_whitespace=False, names=["sepal length", "sepal width", "petal length", "petal width", "class"])
print(type(data));print(data.iloc[0:10,:])

<class 'pandas.core.frame.DataFrame'>
   sepal length  sepal width  petal length  petal width        class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa
5           5.4          3.9           1.7          0.4  Iris-setosa
6           4.6          3.4           1.4          0.3  Iris-setosa
7           5.0          3.4           1.5          0.2  Iris-setosa
8           4.4          2.9           1.4          0.2  Iris-setosa
9           4.9          3.1           1.5          0.1  Iris-setosa


## 2. 数据选取与描述性统计分析

In [ ]:
x = data.iloc[0:3,0:2];print(x)
data.iloc[:,0:2].describe()

注：还是那个索引的问题，min:max过程中min可以取到，max不行

## 3. 计算列的相关系数

In [ ]:
data.corr(method="pearson")#此时为皮尔逊相关系数

## 4. 去除重复

In [ ]:
data["sepal length"].unique()

## 5. 按照条件选择数据的部分列

In [ ]:
data[[x for x in data.columns if 'width' in x]].iloc[0:10,:]#本例的本质是筛选出列的名字

## 6. 去除含有nan的行（列）

In [18]:
import numpy as np
data.iloc[1:5,2]=np.nan#指定一些nan，注意字符“nan”与nan数据格式不同
print(data.iloc[0:10,:])

data1=data.dropna(axis=0,how='any')#去除含有nan的行（去除全是nan的行"any"改为“all”）
print(data1.iloc[0:10,:])

data2=data.dropna(axis=1,how='any')#去除含有nan的列（去除全是nan的列"any"改为“all”）
print(data2.iloc[0:10,:])

   sepal length  sepal width  petal length  petal width        class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           NaN          0.2  Iris-setosa
2           4.7          3.2           NaN          0.2  Iris-setosa
3           4.6          3.1           NaN          0.2  Iris-setosa
4           5.0          3.6           NaN          0.2  Iris-setosa
5           5.4          3.9           1.7          0.4  Iris-setosa
6           4.6          3.4           1.4          0.3  Iris-setosa
7           5.0          3.4           1.5          0.2  Iris-setosa
8           4.4          2.9           1.4          0.2  Iris-setosa
9           4.9          3.1           1.5          0.1  Iris-setosa
    sepal length  sepal width  petal length  petal width        class
0            5.1          3.5           1.4          0.2  Iris-setosa
5            5.4          3.9           1.7          0.4  Iris-setosa
6            4.6          3.4  

## 7. 按照某列排序

In [27]:
print(data.iloc[0:10,:])
data=data.sort_values(by='sepal width',axis=0,ascending=False)#从大到小排序
print(data.iloc[0:10,:])

   sepal length  sepal width  petal length  petal width        class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa
5           5.4          3.9           1.7          0.4  Iris-setosa
6           4.6          3.4           1.4          0.3  Iris-setosa
7           5.0          3.4           1.5          0.2  Iris-setosa
8           4.4          2.9           1.4          0.2  Iris-setosa
9           4.9          3.1           1.5          0.1  Iris-setosa
     sepal length  sepal width  petal length  petal width           class
15            5.7          4.4           1.5          0.4     Iris-setosa
33            5.5          4.2           1.4          0.2     Iris-setosa
32            5.2  